---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2020/11/22 12:26
---

---@class LoadingCtrl
local LoadingCtrl = {}

function LoadingCtrl:New()
    self.viewUrl = ViewConfig.Loading
end

print("LoadingCtrl")
