---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2020/11/22 12:20
---

---@class LoadingView
local LoadingView = {}

function LoadingView.Awake()

end

function LoadingView.Start()

end

function LoadingView.OnDestroy()

end

return LoadingView
