---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2020/11/30 13:49
---


require('ctrl.LoadingCtrl')

local CtrlManager = {}

local ctrls = {}

function CtrlManager:Init()
    print('Lua CtrlManager Init')
    local ctrlPath = 'ctrl/LoadingCtrl.lua'
end



return CtrlManager