---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2020/11/22 11:52
---
require("Default")

---@class Main
local Main = {}

function Main.Init()
    print(' 启动游戏 ')
end

function Main.LoadLoading()
    print(' 加载Loading ')
end

Main.Init()


