---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2020/11/22 11:53
---

require('common.CtrlManager')

XLuaResourceManager = CS.UnityLua.XLuaResourceManager.Instance()
print(CS.UnityLua)
print(CS.UnityLua.XLuaResourceManager)
print(XLuaResourceManager)

